version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:2.5
              environment:
                  RAILS_ENV: test
                  SCHOLARSARCHIVE_DB_PASSWORD: ''
                  SCHOLARSARCHIVE_DB_PORT: '3306'
                  SCHOLARSARCHIVE_DB_USERNAME: root
                  SCHOLARSARCHIVE_DB_HOST: 127.0.0.1
            - image: circleci/mysql:5.7.22
              environment:
                  MYSQL_DATABASE: sa_test
        working_directory: ~/app
        steps:
            - run:
                  name: Update Debian Packages
                  command: |
                      echo "deb http://http.debian.net/debian stretch main" | sudo tee -a /etc/apt/sources.list
                      sudo apt-get update -qq
                      sudo apt-get upgrade -qq
                      sudo apt-get install -y -f software-properties-common build-essential default-libmysqlclient-dev mariadb-client nodejs make apt-utils
                      sudo apt-get install -t stretch -y openjdk-8-jre-headless ca-certificates-java
                      sudo apt-get install -y openjdk-8-jre openjdk-8-jdk openjdk-8-jdk-headless
                      sudo update-alternatives --config java
            - checkout
            - restore_cache:
                  key: gemfile-{{ checksum "Gemfile.lock" }}
            - run:
                  name: Install Ruby Dependencies
                  command: bundle check --without production staging --path=vendor/bundle || bundle install --without production staging --path=vendor/bundle --jobs=4 --retry=3
            - run: |
                  sudo gem install fcrepo_wrapper
                  sudo gem install solr_wrapper
            - run:
                  name: Start SOLR
                  command: solr_wrapper -n hydra-test -p 8985 --version 6.6.1
                  background: true
            - run:
                  name: Start FCREPO
                  command: fcrepo_wrapper -p 8986 --no-jms
                  background: true
            - run:
                  name: Run Rubocop
                  command: bundle exec rubocop
            - save_cache:
                  key: gemfile-{{ checksum "Gemfile.lock" }}
                  paths:
                      - vendor/bundle
                      - tmp/zips
            - run:
                  name: Giving SOLR and FCREPO time to spin up
                  command: sleep 10
            - run:
                  name: Wait for DB
                  command: dockerize -wait tcp://localhost:3306 -timeout 1m
            - run:
                  name: Create DB
                  command: bundle exec rake db:create db:schema:load --trace
            - run:
                  name: Run Tests
                  command: |
                      bundle exec rspec --profile 10 \
                                        --format RspecJunitFormatter \
                                        --out /tmp/test-results/rspec.xml \
                                        --format progress \
                                        $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            - store_artifacts:
                  path: coverage
                  destination: coverage
            - store_test_results:
                  path: /tmp/circle-junit
