terms:
    - id: http://creativecommons.org/licenses/by/3.0/us/
      term: Attribution 3.0 United States
      active: false
    - id: http://creativecommons.org/licenses/by-sa/3.0/us/
      term: Attribution-ShareAlike 3.0 United States
      active: false
    - id: http://creativecommons.org/licenses/by-nc/3.0/us/
      term: Attribution-NonCommercial 3.0 United States
      active: false
    - id: http://creativecommons.org/licenses/by-nd/3.0/us/
      term: Attribution-NoDerivs 3.0 United States
      active: false
    - id: http://creativecommons.org/licenses/by-nc-nd/3.0/us/
      term: Attribution-NonCommercial-NoDerivs 3.0 United States
      active: false
    - id: http://creativecommons.org/licenses/by-nc-sa/3.0/us/
      term: Attribution-NonCommercial-ShareAlike 3.0 United States
      active: false
    - id: http://creativecommons.org/licenses/by/4.0/
      term: Attribution 4.0 (CC BY 4.0)
      active: true
    - id: http://creativecommons.org/licenses/by-sa/4.0/
      term: Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
      active: true
    - id: http://creativecommons.org/licenses/by-nc/4.0/
      term: Attribution-NonCommercial 4.0 (CC BY-NC 4.0)
      active: true
    - id: http://creativecommons.org/licenses/by-nd/4.0/
      term: Attribution-NoDerivatives 4.0 (CC BY-ND 4.0)
      active: true
    - id: http://creativecommons.org/licenses/by-nc-nd/4.0/
      term: Attribution-NonCommercial-NoDerivatives 4.0 (CC BY-NC-ND 4.0)
      active: true
    - id: http://creativecommons.org/licenses/by-nc-sa/4.0/
      term: Attribution-NonCommercial-ShareAlike 4.0 (CC BY-NC-SA 4.0)
      active: true
    - id: http://creativecommons.org/publicdomain/mark/1.0/
      term: Public Domain Mark 1.0
      active: true
    - id: http://creativecommons.org/publicdomain/zero/1.0/
      term: CC0 1.0 Universal
      active: true
    - id: http://www.europeana.eu/portal/rights/rr-r.html
      term: All rights reserved
      active: true
    - id: https://opensource.org/licenses/MIT
      term: MIT
      active: true
    - id: https://opensource.org/licenses/Apache-2.0
      term: Apache 2.0
      active: true