#This file is in the order of `ModelName: "Admin Set Name"`
#If changes are being made to this file, please follow this order

Article: "Article"
BatchUploadItem: "Batch Upload Item"
GraduateThesisOrDissertation: "Graduate Thesis Or Dissertation"
GraduateProject: "Graduate Project"
HonorsCollegeThesis: "Honors College Theses"
UndergraduateThesisOrProject: "Undergraduate Thesis Or Project"
EescPublication: "Eesc Publication"
TechnicalReport: "Technical Report"
Dataset: "Dataset"
OpenEducationalResource: "Open Educational Resource"
AdministrativeReportOrPublication: "Administrative Report Or Publication"
ConferenceProceedingsOrJournal: "Conference Proceedings Or Journal"
Default: "Default"
