#
# To integrate your app with Google Analytics, uncomment the lines below and add your API key information.
#
# analytics:
#   app_name: <%= ENV.fetch('GOOGLE_OAUTH_APP_NAME', nil) %>
#   app_version: <%= ENV.fetch('GOOGLE_OAUTH_APP_VERSION', nil) %>
#   privkey_path: <%= ENV.fetch('GOOGLE_OAUTH_PRIVATE_KEY_PATH', nil) %>
#   privkey_secret: <%= ENV.fetch('GOOGLE_OAUTH_PRIVATE_KEY_SECRET', nil) %>
#   client_email: <%= ENV.fetch('GOOGLE_OAUTH_CLIENT_EMAIL', nil) %>
