staging:
  adapter: solr
  url: <%= ENV['SCHOLARSARCHIVE_SOLR_URL'] || "http://127.0.0.1:8983/solr/hydra-staging" %>
development:
  adapter: solr
  url: <%= ENV['SCHOLARSARCHIVE_SOLR_URL'] || "http://127.0.0.1:8983/solr/hydra-development" %>
test: &test
  adapter: solr
  url: <%= ENV['SCHOLARSARCHIVE_TEST_SOLR_URL'] || "http://127.0.0.1:8985/solr/hydra-test" %>
production:
  adapter: solr
  url: <%= ENV['SCHOLARSARCHIVE_SOLR_URL'] || "http://127.0.0.1:8983/solr/hydra-prod" %>

