development:
  adapter: solr
  url: <%= ENV['SCHOLARSARCHIVE_SOLR_URL'] || "http://127.0.0.1:8983/solr/development" %>
test: &test
  adapter: solr
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/test" %>
production:
  adapter: solr
  url: <%= ENV['SCHOLARSARCHIVE_SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>
staging:
  adapter: solr
  url: <%= ENV['SCHOLARSARCHIVE_SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>
