# cable.yml
development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV.fetch('SCHOLARSARCHIVE_URL_REDIS', 'redis://localhost:6379') %>/1

production:
  adapter: redis
  url: <%= ENV.fetch('SCHOLARSARCHIVE_URL_REDIS', 'redis://localhost:6379') %>/1
