rubycas:
  cas_base_url: https://cas.myorganization.com
  validate_url: https://cas.myorganization.com/cas/samlValidate
  cas_destination_logout_param_name: url

# Configurations for types of notification, such as a daily cron to handle
# lifting embargoes. Find this in lib/tasks/process_embargoes.rake
notifications:
  # ActionMailer needs to understand the server host in order to generate links
  url_host: <%= ENV['SCHOLARSARCHIVE_WWW_HOST'] || 'localhost' %>
  support_email: <%= ENV['SCHOLARSARCHIVE_SUPPORT_EMAIL'] || 'libtech.support@oregonstate.edu' %>
  # Configuration specific to the embargoes lifting functionality
  embargoes_lifting:
    from: 'noreply@oregonstate.edu'
    to: <%= ENV['SCHOLARSARCHIVE_EMBARGOES_LIFTING_EMAILS'] || 'noreply@oregonstate.edu' %>
    subject: "[Scholars Archive] Daily Embargoes Lifting Status"
