# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: <%= ENV.fetch('SCHOLARSARCHIVE_ADAPTER', "sqlite3") %>
  pool: 5
  timeout: 5000
  <% unless ENV.fetch('SCHOLARSARCHIVE_ADAPTER', 'sqlite3').casecmp('sqlite3').zero? %>
  database: <%= ENV.fetch('SCHOLARSARCHIVE_DB') %>
  encoding: utf8
  reconnect: true
  username: <%= ENV.fetch('SCHOLARSARCHIVE_DB_USERNAME') %>
  password: <%= ENV.fetch('SCHOLARSARCHIVE_DB_PASSWORD') %>
  host: <%= ENV.fetch('SCHOLARSARCHIVE_DB_HOST') %>
  port: <%= ENV.fetch('SCHOLARSARCHIVE_DB_PORT', 3306) %>
  <% end %>

development:
  <<: *default
  <% if ENV.fetch('SCHOLARSARCHIVE_ADAPTER', 'sqlite3').casecmp('sqlite3').zero? %>
  database: 'db/development.sqlite3'
  <% else %>
  host: <%= ENV.fetch('SCHOLARSARCHIVE_DB_HOST', 'localhost') == 'localhost' ? 'localhost' : 'db' %>
  database: <%= ENV.fetch('SCHOLARSARCHIVE_DB_HOST', 'localhost') == 'localhost' ? ENV.fetch('SCHOLARSARCHIVE_DB') : 'development' %>
  <% end %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  <% if ENV.fetch('SCHOLARSARCHIVE_ADAPTER', 'sqlite3').casecmp('sqlite3').zero? %>
  database: 'db/test.sqlite3'
  <% else %>
  host: <%= ENV.fetch('SCHOLARSARCHIVE_DB_HOST', 'localhost') == 'localhost' ? 'localhost' : 'db' %>
  database: <%= ENV.fetch('SCHOLARSARCHIVE_DB_HOST', 'localhost') == 'localhost' ? ENV.fetch('SCHOLARSARCHIVE_DB') : 'development' %>
  <% end %>

production: &production
  <<: *default

staging:
  <<: *production
