# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: <%= ENV.fetch('SCHOLARSARCHIVE_DB', 'sa_development') %>
  encoding: utf8
  reconnect: true
  username: <%= ENV.fetch('SCHOLARSARCHIVE_DB_USERNAME', 'root') %>
  password: <%= ENV.fetch('SCHOLARSARCHIVE_DB_PASSWORD', '12341234') %>
  host: <%= ENV.fetch('SCHOLARSARCHIVE_DB_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('SCHOLARSARCHIVE_DB_PORT', 3306) %>

development:
  <<: *default
  # If ENV is localhost or 127.0.0.1 then it is assumed to not be running docker, so force 127.0.0.1
  host: <%= %w(localhost 127.0.0.1).include?(ENV.fetch('SCHOLARSARCHIVE_DB_HOST', '127.0.0.1')) ? '127.0.0.1' : 'db' %>
  # If ENV is localhost or 127.0.0.1 then it is assumed to not be running docker, so use a unique database name
  database: <%= %w(localhost 127.0.0.1).include?(ENV.fetch('SCHOLARSARCHIVE_DB_HOST', '127.0.0.1')) ? 'development' : 'sa_development' %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  # README: If ENV is localhost or 127.0.0.1 then it is assumed to not be running docker, so force 127.0.0.1 which is critical for circleci2
  host: <%= %w(localhost 127.0.0.1).include?(ENV.fetch('SCHOLARSARCHIVE_DB_HOST', '127.0.0.1')) ? '127.0.0.1' : 'db_test' %>
  # If ENV is localhost or 127.0.0.1 then it is assumed to not be running docker, so use a unique database name
  database: <%= %w(localhost 127.0.0.1).include?(ENV.fetch('SCHOLARSARCHIVE_DB_HOST', '127.0.0.1')) ? 'sa_test' : 'test' %>

production: &production
  <<: *default
  pool: <%= ENV.fetch('SCHOLARSARCHIVE_DB_POOL', 50) %>

staging:
  <<: *production
