#Development using fcrepo_wrapper
development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['SCHOLARSARCHIVE_FEDORA_URL'] || "http://127.0.0.1:8984/rest" %>
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['SCHOLARSARCHIVE_FEDORA_URL'] || "http://127.0.0.1:8986/rest" %>
  base_path: /test

#Production / Staging hosted behind a web server
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['SCHOLARSARCHIVE_FEDORA_URL'] || "http://127.0.0.1:8080/fcrepo/rest" %>
  base_path: /prod
staging:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['SCHOLARSARCHIVE_FEDORA_URL'] || "http://127.0.0.1:8080/fcrepo/rest" %>
  base_path: /staging
