development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://<%= ENV['SCHOLARSARCHIVE_FEDORA_HOST'] || 'localhost' %>:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8984 %>/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://<%= ENV['SCHOLARSARCHIVE_FEDORA_HOST'] || 'localhost' %>:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8986 %>/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['SCHOLARSARCHIVE_FEDORA_URL'] %>
  base_path: /prod
  request: { timeout: 1000, open_timeout: 1000}
staging:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['SCHOLARSARCHIVE_FEDORA_URL'] %>
  base_path: /staging
  request: { timeout: 1000, open_timeout: 1000}
