staging:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['SCHOLARSARCHIVE_FEDORA_URL'] || "http://127.0.0.1:8080/fcrepo/rest" %>
  base_path: /staging
development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 9984 %>/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['FCREPO_TEST_PORT'] || 9984 %>/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['SCHOLARSARCHIVE_FEDORA_URL'] || "http://127.0.0.1:8080/fcrepo/rest" %>
  base_path: /prod
