development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('SCHOLARSARCHIVE_FEDORA_URL', 'http://localhost:8984/fcrepo/rest/dev') %>
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('SCHOLARSARCHIVE_FEDORA_URL', 'http://localhost:8080/fcrepo/rest/test') %>
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('SCHOLARSARCHIVE_FEDORA_URL', 'http://localhost:8080/fcrepo/rest/prod') %>
  request: { timeout: 1000, open_timeout: 1000 }
staging:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('SCHOLARSARCHIVE_FEDORA_URL', 'http://localhost:8080/fcrepo/rest/staging') %>
  request: { timeout: 1000, open_timeout: 1000 }
