development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('SCHOLARSARCHIVE_FEDORA_URL', 'http://localhost:8984') %>/fcrepo/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('SCHOLARSARCHIVE_FEDORA_URL', 'http://localhost:8986') %>/fcrepo/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('SCHOLARSARCHIVE_FEDORA_URL', 'http://localhost:8080') %>/rest
  base_path: /prod
  request: { timeout: 1000, open_timeout: 1000 }
staging:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV.fetch('SCHOLARSARCHIVE_FEDORA_URL', 'http://localhost:8080') %>/rest
  base_path: /staging
  request: { timeout: 1000, open_timeout: 1000 }
