development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8984 %>/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['SCHOLARSARCHIVE_FEDORA_URL'] %>
  base_path: /prod
  request: { timeout: 1000, open_timeout: 100}
staging:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['SCHOLARSARCHIVE_FEDORA_URL'] %>
  base_path: /staging
