# 10th IIFET Conference, July 10-14, 2000, Corvallis, Oregon, U.S.A.  
 "30554": "http://ir.library.oregonstate.edu/"
# 11th IIFET Conference, August 19-22, 2002, Wellington, New Zealand  
 "56900": "http://ir.library.oregonstate.edu/"
# 12th IIFET Conference, July 20-30, 2004, Tokyo, Japan  
 "56398": "http://ir.library.oregonstate.edu/"
# 13th IIFET Conference, July 11-14, 2006, Portsmouth, UK  
 "43173": "http://ir.library.oregonstate.edu/"
# 14th IIFET Conference, July 22-25, 2008, Nha Trang, Vietnam  
 "36185": "http://ir.library.oregonstate.edu/"
# 15th IIFET Conference, July 13-16, 2010, Montpellier, France  
 "38399": "http://ir.library.oregonstate.edu/"
# 16th IIFET Conference, July 16-20, 2012, Dar es Salaam, Tanzania  
 "32180": "http://ir.library.oregonstate.edu/"
# 17th IIFET Conference, July 7-11, 2014, Brisbane, Australia  
 "52603": "http://ir.library.oregonstate.edu/"
# 18th IIFET Conference, July 11-15, 2016, Aberdeen, Scotland, UK  
 "59918": "http://ir.library.oregonstate.edu/"
# 8th IIFET Conference, July 1-4, 1996, Marrakech, Morocco  
 "56895": "http://ir.library.oregonstate.edu/"
# College of Earth, Ocean, and Atmospheric Sciences  
 "1309": "http://ir.library.oregonstate.edu/"
# Department of Forest Engineering, Resources and Management  
 "10900": "http://ir.library.oregonstate.edu/"
# Department of Women, Gender and Sexuality  
 "18602": "http://ir.library.oregonstate.edu/"
# Difference, Power and Discrimination  
 "46366": "http://ir.library.oregonstate.edu/"
# Office of Student Affairs Research, Evaluation, and Planning  
 "1344": "http://ir.library.oregonstate.edu/"
# School of Chemical, Biological and Environmental Engineering  
 "16183": "http://ir.library.oregonstate.edu/"
# School of Mechanical, Industrial & Manufacturing Engineering  
 "14319": "http://ir.library.oregonstate.edu/"
# Student Affairs, Division of  
 "955": "http://ir.library.oregonstate.edu/"
# Baseball  
 "3925": "http://ir.library.oregonstate.edu/"
# Center for Genome Research & Biocomputing  
 "42305": "http://ir.library.oregonstate.edu/"
# Chinese Disinterment Documents  
 "21890": "http://ir.library.oregonstate.edu/"
# College of Agricultural Sciences  
 "13588": "http://ir.library.oregonstate.edu/"
# College of Business  
 "8148": "http://ir.library.oregonstate.edu/"
# College of Education  
 "18087": "http://ir.library.oregonstate.edu/"
# College of Forestry/Oregon Forest Research Laboratory (FRL)  
 "7530": "http://ir.library.oregonstate.edu/"
# College of Pharmacy  
 "17743": "http://ir.library.oregonstate.edu/"
# College of Public Health and Human Sciences  
 "28634": "http://ir.library.oregonstate.edu/"
# College of Veterinary Medicine  
 "12904": "http://ir.library.oregonstate.edu/"
# Commodity Data Sheets  
 "48174": "http://ir.library.oregonstate.edu/"
# Conferences (Rural-Urban Connections)  
 "10431": "http://ir.library.oregonstate.edu/"
# Darlene Hooley Papers  
 "14383": "http://ir.library.oregonstate.edu/"
# Datasets  
 "40396": "http://ir.library.oregonstate.edu/"
# Department of Agricultural Education and Agricultural Sciences  
 "18498": "http://ir.library.oregonstate.edu/"
# Department of Animal and Rangeland Science  
 "18827": "http://ir.library.oregonstate.edu/"
# Department of Anthropology  
 "6366": "http://ir.library.oregonstate.edu/"
# Department of Applied Economics  
 "14947": "http://ir.library.oregonstate.edu/"
# Department of Art  
 "21991": "http://ir.library.oregonstate.edu/"
# Department of Biochemistry and Biophysics  
 "19990": "http://ir.library.oregonstate.edu/"
# Department of Biological and Ecological Engineering  
 "494": "http://ir.library.oregonstate.edu/"
# Department of Biomedical Sciences  
 "30116": "http://ir.library.oregonstate.edu/"
# Department of Bioresource Research  
 "6762": "http://ir.library.oregonstate.edu/"
# Department of Botany and Plant Pathology  
 "1932": "http://ir.library.oregonstate.edu/"
# Department of Chemistry  
 "17746": "http://ir.library.oregonstate.edu/"
# Department of Crop & Soil Science  
 "14728": "http://ir.library.oregonstate.edu/"
# Department of Design and Human Environment  
 "14777": "http://ir.library.oregonstate.edu/"
# Department of Economics  
 "14945": "http://ir.library.oregonstate.edu/"
# Department of English  
 "18071": "http://ir.library.oregonstate.edu/"
# Department of Environmental & Molecular Toxicology  
 "25639": "http://ir.library.oregonstate.edu/"
# Department of Ethnic Studies  
 "21412": "http://ir.library.oregonstate.edu/"
# Department of Exercise and Sport Science  
 "19834": "http://ir.library.oregonstate.edu/"
# Department of Fisheries and Wildlife  
 "12558": "http://ir.library.oregonstate.edu/"
# Department of Food Science and Technology  
 "17881": "http://ir.library.oregonstate.edu/"
# Department of Foreign Languages and Literatures  
 "24915": "http://ir.library.oregonstate.edu/"
# Department of Forest Ecosystems and Society  
 "10899": "http://ir.library.oregonstate.edu/"
# Department of History  
 "12720": "http://ir.library.oregonstate.edu/"
# Department of Horticulture  
 "16374": "http://ir.library.oregonstate.edu/"
# Department of Human Development and Family Sciences  
 "18472": "http://ir.library.oregonstate.edu/"
# Department of Integrative Biology  
 "52699": "http://ir.library.oregonstate.edu/"
# Department of Mathematics  
 "13737": "http://ir.library.oregonstate.edu/"
# Department of Medical Physics  
 "19605": "http://ir.library.oregonstate.edu/"
# Department of Microbiology  
 "9972": "http://ir.library.oregonstate.edu/"
# Department of Music  
 "10687": "http://ir.library.oregonstate.edu/"
# Department of Nuclear Engineering and Radiation Health Physics  
 "18496": "http://ir.library.oregonstate.edu/"
# Department of Nutrition  
 "25873": "http://ir.library.oregonstate.edu/"
# Department of Philosophy  
 "21416": "http://ir.library.oregonstate.edu/"
# Department of Physics  
 "13831": "http://ir.library.oregonstate.edu/"
# Department of Public Health  
 "11402": "http://ir.library.oregonstate.edu/"
# Department of Rangeland Ecology and Management  
 "7887": "http://ir.library.oregonstate.edu/"
# Department of Science and Mathematics Education  
 "8307": "http://ir.library.oregonstate.edu/"
# Department of Sociology  
 "28891": "http://ir.library.oregonstate.edu/"
# Department of Speech Communication  
 "11957": "http://ir.library.oregonstate.edu/"
# Department of Statistics  
 "18467": "http://ir.library.oregonstate.edu/"
# Department of Toxicology  
 "18862": "http://ir.library.oregonstate.edu/"
# Department of Wood Science & Engineering  
 "4573": "http://ir.library.oregonstate.edu/"
# Department of Zoology  
 "12721": "http://ir.library.oregonstate.edu/"
# Electronic Theses and Dissertations  
 "88": "http://ir.library.oregonstate.edu/"
# Engineering Experiment Station  
 "30412": "http://ir.library.oregonstate.edu/"
# Environmental Science Program  
 "15880": "http://ir.library.oregonstate.edu/"
# Ethnographic Field School (ANTH 499/599)  
 "6367": "http://ir.library.oregonstate.edu/"
# Extended Campus (Ecampus)  
 "59941": "http://ir.library.oregonstate.edu/"
# Extension Service and Agricultural Experiment Station  
 "3904": "http://ir.library.oregonstate.edu/"
# Facilities Services  
 "16345": "http://ir.library.oregonstate.edu/"
# Faculty Research  
 "3004": "http://ir.library.oregonstate.edu/"
# Faculty Research  
 "59893": "http://ir.library.oregonstate.edu/"
# Forest Research Laboratory  
 "7543": "http://ir.library.oregonstate.edu/"
# Geography  
 "1721": "http://ir.library.oregonstate.edu/"
# Geology  
 "7889": "http://ir.library.oregonstate.edu/"
# HMSC Administrative Work  
 "13844": "http://ir.library.oregonstate.edu/"
# Hatfield Marine Science Center  
 "1317": "http://ir.library.oregonstate.edu/"
# Honors College Publications  
 "15190": "http://ir.library.oregonstate.edu/"
# Independent Multidisciplinary Science Team (IMST)  
 "11269": "http://ir.library.oregonstate.edu/"
# Information Services  
 "58587": "http://ir.library.oregonstate.edu/"
# Institute for Natural Resources (INR)  
 "11": "http://ir.library.oregonstate.edu/"
# Interdisciplinary Studies  
 "7144": "http://ir.library.oregonstate.edu/"
# Library Committee  
 "1747": "http://ir.library.oregonstate.edu/"
# Linus Pauling Institute  
 "36900": "http://ir.library.oregonstate.edu/"
# Marine Renewable Energy  
 "13496": "http://ir.library.oregonstate.edu/"
# NAAFE Forum 2015  
 "56425": "http://ir.library.oregonstate.edu/"
# Natural Resources  
 "5": "http://ir.library.oregonstate.edu/"
# OSU Cultural Resource Centers  
 "27565": "http://ir.library.oregonstate.edu/"
# OSU Press  
 "18856": "http://ir.library.oregonstate.edu/"
# OSU's WWII Era Japanese American Students  
 "36408": "http://ir.library.oregonstate.edu/"
# Office of Institutional Research  
 "1905": "http://ir.library.oregonstate.edu/"
# Open Access Articles  
 "43908": "http://ir.library.oregonstate.edu/"
# Open Educational Resources  
 "57911": "http://ir.library.oregonstate.edu/"
# Oregon Biodiversity Information Center (ORBIC)  
 "27": "http://ir.library.oregonstate.edu/"
# Oregon Department of Fish and Wildlife  
 "16917": "http://ir.library.oregonstate.edu/"
# Oregon Estuaries  
 "21994": "http://ir.library.oregonstate.edu/"
# Oregon Game Commission Publications  
 "43060": "http://ir.library.oregonstate.edu/"
# Oregon Hops and Brewing Archives  
 "49145": "http://ir.library.oregonstate.edu/"
# Oregon Sea Grant  
 "42614": "http://ir.library.oregonstate.edu/"
# Oregon State Arthropod Collection  
 "13788": "http://ir.library.oregonstate.edu/"
# Oregon Wine Research Institiute  
 "58155": "http://ir.library.oregonstate.edu/"
# President's Office  
 "4839": "http://ir.library.oregonstate.edu/"
# Professional Science Master's Program  
 "29546": "http://ir.library.oregonstate.edu/"
# Program in Water Conflict Management and Transformation  
 "11272": "http://ir.library.oregonstate.edu/"
# Registrar's Office  
 "2049": "http://ir.library.oregonstate.edu/"
# Research Communications  
 "1422": "http://ir.library.oregonstate.edu/"
# Rural Studies Program  
 "8335": "http://ir.library.oregonstate.edu/"
# Rural-Urban Connections  
 "9951": "http://ir.library.oregonstate.edu/"
# School of Civil and Construction Engineering  
 "22529": "http://ir.library.oregonstate.edu/"
# School of Electrical Engineering and Computer Science  
 "7302": "http://ir.library.oregonstate.edu/"
# School of Nuclear Science and Engineering  
 "57713": "http://ir.library.oregonstate.edu/"
# School of Psychological Science (Psychology)  
 "36300": "http://ir.library.oregonstate.edu/"
# School of Public Policy  
 "4128": "http://ir.library.oregonstate.edu/"
# Serials  
 "10092": "http://ir.library.oregonstate.edu/"
# Special Collections & Archives Research Center  
 "1891": "http://ir.library.oregonstate.edu/"
# Student Research  
 "2871": "http://ir.library.oregonstate.edu/"
# Track and Field  
 "20816": "http://ir.library.oregonstate.edu/"
# Undergraduate Theses and Research  
 "7": "http://ir.library.oregonstate.edu/"
# University Housing & Dining Services  
 "13696": "http://ir.library.oregonstate.edu/"
# University Information Technology Committee  
 "9135": "http://ir.library.oregonstate.edu/"
# University Libraries  
 "3": "http://ir.library.oregonstate.edu/"
# Urban League of Portland  
 "22017": "http://ir.library.oregonstate.edu/"
# Water Research  
 "12250": "http://ir.library.oregonstate.edu/"
# Water Resources Graduate Program  
 "30755": "http://ir.library.oregonstate.edu/"
# Water Resources Graduate Program  
 "30755": "http://ir.library.oregonstate.edu/"
# Women's Center  
 "11243": "http://ir.library.oregonstate.edu/"
# Writing Intensive Curriculum  
 "15952": "http://ir.library.oregonstate.edu/"