SCHOLARSARCHIVE_ADAPTER: youmustchangethis
SCHOLARSARCHIVE_DB: youmustchangethis
SCHOLARSARCHIVE_DB_HOST: youmustchangethis
SCHOLARSARCHIVE_DB_PASSWORD: youmustchangethis
SCHOLARSARCHIVE_DB_PORT: youmustchangethis
SCHOLARSARCHIVE_DB_USERNAME: youmustchangethis
SCHOLARSARCHIVE_REDIS_HOST: youmustchangethis
SCHOLARSARCHIVE_REDIS_PORT: youmustchangethis
SCHOLARSARCHIVE_SECRET_KEY_BASE: youmustchangethis
SCHOLARSARCHIVE_CAS_BASE_URL: youmustchangethis
SCHOLARSARCHIVE_CAS_VALIDATE_URL: youmustchangethis
SCHOLARSARCHIVE_TRIPLESTORE_ADAPTER_TYPE: youmustchangethis
SCHOLARSARCHIVE_TRIPLESTORE_ADAPTER_URI: youmustchangethis
HTTP_D2H_AUTHENTICATION_TOKEN: youmustchangethis
HTTP_D2H_AUTHENTICATION_USERNAME: youmustchangethis

