# Background job queue
# Docker
#ACTIVE_JOB_QUEUE_ADAPTER: sidekiq

# File characterization
# Docker
#FITS_PATH: /opt/fits-1.0.5/fits.sh

# Rails defaults
# Docker
#RAILS_CACHE_STORE_URL: memcache
#RAILS_LOG_TO_STDOUT: 'true'

# Database
SCHOLARSARCHIVE_DB_PASSWORD: '12341234'
SCHOLARSARCHIVE_DB_PORT: '3306'
SCHOLARSARCHIVE_DB_USERNAME: root
SCHOLARSARCHIVE_DB_HOST: 127.0.0.1
# Docker
#SCHOLARSARCHIVE_DB_HOST: db
# Production/Staging only; not needed for development/test as these are set in database.yml
#SCHOLARSARCHIVE_DB: development

# Fedora repository server
SCHOLARSARCHIVE_FEDORA_URL: http://localhost:8984
# Docker
#SCHOLARSARCHIVE_FEDORA_URL: http://fcrepo:8080

# SOLR index server
SCHOLARSARCHIVE_SOLR_URL: http://localhost:8983
# Docker
#SCHOLARSARCHIVE_SOLR_URL: http://solr:8983

# Redis for background jobs and notifications
SCHOLARSARCHIVE_REDIS_PORT: '6379'
SCHOLARSARCHIVE_REDIS_HOST: localhost
# Docker
#SCHOLARSARCHIVE_REDIS_HOST: redis

# Triplestore adapter cache
SCHOLARSARCHIVE_TRIPLESTORE_ADAPTER_TYPE: blazegraph
SCHOLARSARCHIVE_TRIPLESTORE_ADAPTER_URL: 'http://127.0.0.1:9999/blazegraph/namespace/<%= ENV.fetch('RAILS_ENV') %>/sparql'
# Docker
#SCHOLARSARCHIVE_TRIPLESTORE_ADAPTER_URL: 'http://blazegraph:8080/bigdata/namespace/<%= ENV.fetch('RAILS_ENV') %>/sparql'

# Secret key for Devise and Rails security
SCHOLARSARCHIVE_SECRET_KEY_BASE: bobross1234bobross1234bobross1234bobross1234bobross1234

# CAS authentication
SCHOLARSARCHIVE_CAS_BASE_URL: 'https://FQDN/cas'
SCHOLARSARCHIVE_CAS_VALIDATE_URL: 'https://FQDN/cas/samlValidate'

# Default selected Admin Set on work form
SCHOLARSARCHIVE_DEFAULT_ADMIN_SET: 'Default Admin Set'

# DSpace2Hydra Migration User for API access, bypasses CAS authentication. 'USERNAME' requires a matching entry
# in the users table
HTTP_D2H_AUTHENTICATION_TOKEN: '12345678901234567890'
HTTP_D2H_AUTHENTICATION_USERNAME: 'bobross@FQDN'

# Adminstrators email address for notifications
SCHOLARSARCHIVE_ADMIN_EMAIL: 'noreply@FQDN'

# The full path to the directory that BrowseEverything uses for uploads, the webserver user must have access to this directory
BROWSEEVERYTHING_FILESYSTEM_PATH: '/tmp/browse-everything'

#Recaptcha configuration
SCHOLARSARCHIVE_RECAPTCHA_SECRET_KEY: 'asdfasdfasdfasdfasdfadsfasdfadfsfa'
SCHOLARSARCHIVE_RECAPTCHA_SITE_KEY: 'asdfasdfadsfasdfasdfasdfasdfasdfad'

# NewRelic application monitoring
NEWRELIC_LICENSE_KEY: thisisnttherealkeyhahaha!!11!1!

# Capistrano deployment log path
SCHOLARSARCHIVE_DEPLOYED_REVISION_LOG: /path/to/app/revisions.log
