triplestore_adapter:
  type: <%= "#{ENV['SCHOLARSARCHIVE_TRIPLESTORE_TYPE'] || 'blazegraph'}" %>
  url: <%= "#{ENV['SCHOLARSARCHIVE_TRIPLESTORE_URL'] || 'http://localhost:9999/blazegraph/namespace/development/sparql'}" %>