---
:concurrency: 5
:pidfile: /data/tmp/pids/sidekiq.pid
:logfile: /proc/self/fd/1
staging:
  :concurrency: <%= ENV.fetch('SCHOLARSARCHIVE_SIDEKIQ_THREADS', 16) %>
production:
  :concurrency: <%= ENV.fetch('SCHOLARSARCHIVE_SIDEKIQ_THREADS', 16) %>
:queues:
  - default
  - [ingest, 2]
