# frozen_string_literal: true

# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::ScholarsArchive::DefaultMetadata
  include ::Hyrax::FileSetBehavior

  private

  def set_defaults; end
end
