# frozen_string_literal: true

# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior
  include ::ScholarsArchive::DefaultMetadata

  private

  def set_defaults
  end
end
